### ISSUE TITLE
stO Dylan Orz

### ISSUE THREAD

**Issue by kalakuer** [DylanLiuH2O/generateInvertibleMatrix#1]
stO Dylan Orz
stO Dylan Orz
stO Dylan Orz
stO Dylan Orz
stO Dylan Orz
stO Dylan Orz
stO Dylan Orz

**Comment by DylanLiuH2O** [comment]
> stO Dylan Orz
> stO Dylan Orz
> stO Dylan Orz
> stO Dylan Orz
> stO Dylan Orz
> stO Dylan Orz
> stO Dylan Orz

(,,#ﾟДﾟ)

**Comment by kalakuer** [comment]
.irvvv7v77i:..                                                                                                                     
                .i71PQQBQRggbPSILr.                                                                                                                   
              :7SbMRBBBQQQBQBQQgZP5Lr.                                                                                                                
           .iJXDQBBBBQRQQBQBBBQBQBMgdKLi.                                                                                                             
          :vqgBQBMZS1LLLJs12PZQQQQBQBRgKJi.                                                                                                           
         .7SDQRBg5r.       ..:iLIERQRgEgdqJr.                                                                                                         
        .iuPRRRdU:              .:7UPEMMQRgP27:                                                                                                       
       .:s5gMQbUi                  .7XDQMQRQMdjr.                                                                                                     
       :vIDMQgq7.                    :sKMQQMQgqLi..                                                                                                   
      .r1EMQgPL:                       r2ggMgMP5svvvri:...    .:iiii:.                                                                                
      .rSgQgdji.                        iUDRgggdEPDgQMRggEbKXIS5bdgDMZqj7ri:.                                                                         
      .vXQMDSL.        ...              .7PBMRgRRQQBBBBBBBBBBBQBBBQBBBBBRgEPIu7i:..                                                                   
      :vbRRES7.         ...              :UgBQQQBMMDDDggRgDPqSKKEdEEggQBBBBQBQQgZP5svi:.                                                              
      :udQgg57.          ..               :uPggRd5vriii7v7i:.....::r7vL2XddDgRRQQQRMZZKIYvi:..                                                        
      iUgMRgSr.       .....                 ::rii:.                      .:rvsIKDgQQQRQMMEEXUvr:.                                                     
     .i5gRgg57.      .:i::.                                        .      .:i7YSPDgQMQggZDEEPPSSJ7:.                     ..... ....                   
     .rUDMRgq7:       .....                                   .:irvvYvvvLLJY115KEZggRMgbKUI2XXPPPKXusr:               ..7jqPP21jI2Isvi.               
      ijPQggPJ:                                          ..iirrJIPXXUUYY77ii::::iri7LIKPXS1uLv7suXPddP2si.      .:rLYJuXZBQBBBQQMQMRZPjr.             
      :vPRRgZ2r.                                        :ivLsvsuSSXUj7ri:..          .i7UIX1Lrii77vLUIKX5vi...:ivUbgQQQQQQBQBBBQBQBQBBBgbur.          
      .rSRgRgPv.                                       .iLJ1jJYJs112I51uL7ri:.....      .rvU22sY7i:::rLI22sv7vY25bZRQBQgKI1IXdDRRBBBQBQBQQEIi.        
       :JKggQgSr.                                      .7j2L7i::iirrrr7vuUSII1IXPU7.       :7s22uri...::rrsJUu2152525uLi:.. ..::r7jIbZQQBQBQP7.       
       .iUqMgRbUi.                                     :v5IJr:...:..   ..irvvj5gQQZI7:       .:7vjYvi:.  .:7vYLsYvri..             .:rsqEQQQRbsi      
       .rjbggMgPJ.                                 ...:rjXZdP2s77i:..         .rSZMbPUv:.       .rLsJ7i.. ..:i7ssr.                    :sPQQQQgui     
      .isPZMgQQEv.                                .i7LLJs25bdDdEqXJYvvi:         :75ZQMDI7:.      .iv21Jr:.. ..:::                      .YKgRQQbv.    
     :v5dDRMQQgJ:                                 :rJujL7irirrJIbddPEbdXjr.       .iSZQQBDPYi.      :r2KKUv:.                            .72gQQbj.    
     r2DMRggP5r:                                 :7USSJ7:.     .iuqggggQQQd5vr.    ..:7XDBQgq1r.      :v2dP5vi.                           .r5ggPv.    
    .rKDRMQqJ:                                  ruqPZK2vi.       .:irirvXZRgZK2Y7i:.    :LKZRDqYi.      :YdgQdUr.                          iSgRSr     
    .YPQgQd1i.                                 :LXqPPP5Sjsrr::..         :i7s1uUJJvr:.    .vIPXI7i..     .7qgQDZSs:.          .:::.       .7PQMSi     
    i1gRQDIi.                                .i711uvLY5PgggbPXK2u7i.         .:ir7YYJvi     .ivJs7r:.      .7YqgQgPv:       ....:..       iugQDu:     
   isPQQM5i                                  .i777iiirv1SqKKSqPZgQgESur:.        .:rLuv:      .:iri:.         :vUEDb2v:     ..           .7PQRS7.     
  .vdgBMXi                                    ...:ii7rri:...::rrs2dgQRZ5Yi:         .::.         .:..           :75PDPj:                 :2ZQDUi      
  :XgQgP7.                                        .i7s7i.        .:r7u1I1usvi.                                   .rIdE5v.               :JPQgdv:      
  rEBgqYi                                          .rYIjvi.            .:ivvLr:                                   :7ISXu7.            .i1PRgZ2r.      
 .sMBgU7.                                          .iY5K2j7:.             .:..                                     :vXPPjr.           i5EQRgXs:       
:rKMRKv:                                             .rv1u1v7::.                                                    :YqPSLi.         :UZQRQP2r.       
v5dRPJ:.                                               .:r7LvsLL7r:.                                                 :7Uujvr:......:72PMggdKvi        
IqMDXr.                                                   .:rLISqKqu7:                                                .ivJUjuYJu25SSPbgDDPXLi         
IdgD2r                                                     ..irsjKPZEqYi                                                :7JU1Uj5KDgQggDDP57:          
qbgE5r.                                                   . ....::rvXPdSL:.                                              .irr:..ivqgQgRZPL:           
dgggIr.                                                  .....     .:rJKPZPu:                                             ..     .rdQMggKv.           
ggQDU:                                              .......           .:LXgDKr.                                                   .JggRgdY:           
DMRDv.                                               ..:..               :ru2I7.                                       ...        .7IZgRd2r.          
EZMKr                                                  ...                :r2KU:                                      ..:.         :JKgMg5L:          
XEd5i                                    .....          .:::..           ..ruPSv.                                      .          .rsPZQMqv:          
qPdUi                                  ..::::..         .:rv1usr:.        .ijKd57.                                               .iv5PDMRqL:          
PgDK7.                                 ..:::..           .:LqMRg27:        .r2KXv:                                               .i1SqXqK27:          
PEMd1i                                ..:....              .7XMQRXY:.       iYIur.                                               .i7JLv7Lvvr:         
v5ERKv.                               .::::.                 :LPZZKJr:.....:i152r.                                               .:i::.:rsjYi.        
i7PRMUi                               ..:::..                 .:v1KSSusYuYYL25q5Y:                                               .::.  .rY2vi         
.r5QQEY:                              ...::i::..                 :rJu2u2US5qPdPqjr.                                             :rri.  .iYY7.         
.:1MBQPv:                               .:7v1uuYv7v7ri:..           .:i:iirLXdDq1r:.                                           :u5j:.  .:r7i:         
 .vRQQDXr.                              .ruPbEPPqqXX55UIuJ7i.              .i2PPu7i:                                          .sbdY:   .:irr:.        
  iKQQRPj:.                             :vqEZ5uYsvJJ2IPEMgdIYi.              :vuUsvi.                                         i1bSr     :rvri.        
   i5QQQdY.                             .LXZSv:.   ..i7u5PbEqSLi.             .ivus7:.                                       .iIq2i    .:7YLi.        
    iqBQBPL.                            .iJ1ji.         ..i7JJs7r::......      .:7JYv:.                                       isXU7.   .i7jvr.        
    .vPQQQZ2r.                           .:7L7:              ..:::.::ir7ri.      :711Y:.                                      .v25Li...:i7v7:.        
      rXBQBQdj:                           .ijUU7i..                 ..iirri.:.....iv5Iji.                                     .rj1Yi:...irvr:         
       iSQMBQD1r             ..            :LPgQZPSUJLri.                ..:.:.....iLXSJ:                                     :7sj7i:..::rrr.         
        :LXZQQRPJ.                          rIMBBBBQBQRZb5u7i.              ..... ..rsXIJi.                                   :v2Ijr:.::rrr:.         
         iugQQQBMu.                         .rubgQBBBBBBBBBBRE2Yr:..            ....:rv55U7:                                  .rjqX1ri:ir7i:          
       .:r1PgMQQQdUr:.                        :i7sU1I2KdMMQQBQBQQDdSUvr:.       :irii::71I2vi.                                  r1PqI7ii77r.          
  .irYsUuuYL7vJSbgEEPKu7.                        .   ..irvvjUPZQQBBBBQDP1srr:::irJU2r:.:iYYvi:                                  .rjK5u7vv7:.          
ri7vju2uYi:.  .:v1dRBBBgKvi.                                ..i71SEgBQBBBQQgd5u77rvr:   :ivLLr:.                                .:v2PPq5Iv:           
1uYLri..        .ivXDQQQDgZqvi.                                 .:i7jXdRQBRZKU7i..      .ivUUuv7r:.                             .:vKZRMgPj:           
5SZqv.           ..:7jKdMBBBBEXvi.            ...                   .:7uXSU7r:.          .rjS5IUjr:                             .:JPQQRgEj:           
1IIu:                .ivUqPDDRggPUr:.         ...:..                  .:::.               .r7sJUs7:.                             .rSZMZgbUi           
Yi.                    ..:rr7vUKgRQdXvr::.     ...:...           .:::.                      .:i7L7r:...                           .iuXEgZ2r.          
.                            .:rv2KddZdEXILr:.       ......... ...::..                         isqK5jL:.                            :LSDdS7:          
                                 ..i7s5KdDMZqsr:.           .                                  .72dPP5v:                             .7UXIsi.         
                                      .:iJqRQBgbjr:.                                             ::rLuv:                              .rY2sr.         
                                          :ruSZgQgZXIYv77ii..                                       :r7i.                              .7s1vi.        
                                             .:vUZRQQMZDZDPU7:.                                      i7vi.                             .:7Jjr:        
                                                ..ir77sjXqZPPI1L7ii..                               .:LuJr:                             .iLLLr:       
                                                       ..i7uSddDbEPPX2sLrrii:i::...      ..:..     .:7UZZSr.                             :rLssr.      
                                                            :ivYu2PPZddqKU212UIuuv7riiirvY2551Yrr:ii7YXgQqr                               :isjv:      
                                                                 ...::irrrr7rrr77LJUuU15IKXqXqS5uJ7v7Y1qXui                               .:v2Yi      
                                                                       .::::::::rvUSPPPPPKSISSPKX2uYsv11U7i                               .:s2Ur.

**Comment by kalakuer** [comment]
.:r7YvJJuYY7ri:................         ... .      ....   ....:rUKEKX517i.        ..::iirii::..                 .              
                    ..:iLUS2UYL7ri:...    .....::::....     .........     .:...     ..:rLJUjJri:..      ...:ii77v7vri:...             .               
       . ...       ..:is2qK5Jvii:...       ..............::iir7vLjjuJusjLY77ii:..    . ..ir77rii:irvYJYsvLYu15SPPPqXuYr:..             . .            
.      ......     ..irsuIU1v7i:..     ...........   ..:ir7Ju5SPPZDgMQQBBBgqjs7vri:..     .ir77vvJ1KdRRRggEEEZEggQRQgDqIvr::.                          
.      ..:.:..    .:rjU5JLrr::..   ......:....   ...:irsuSSqXK5I12uU15SPKPS52S5X2jr:.    .:r712KSKISUIUUjusJJ1UXPggRMRdP5U7i.                         
.      ...:...    .iLUXUvi:....   ....:::::..   ..:ir7ju55S1J7r::.......::rvuUXKPS1r:..:::iivuSS2Lr:..........::rv1IPPddgdXv:.                        
       .......   .:rYS5ur:....   ....:.:.:.......:i77vYJsJv7i:..          .::r7JuUs7rrr7ri:ii777i:.             ..:rrYj5qdKui.                     . .
                ..:ru5SYi.......................irLvY77ii::...               ...::rvUXPX2vr::::..                   .:i7IXXsr.. .                     
                 .:7jX2L:. ..................::irJ12s7::.        .....            :sZBQQbI7i..                       ..rsXSur:....                    
    .         .:r777Lv7i.   ....::i::.. . ...:ir1IXULi..        .....             .7qMBgPjr:.                         .:7YI1Yi:..                   ..
         .   .rKgMSYi:.. .     .iL1ur.   .  .iv5qP2Li:..                     ... ..:rsU5j7:.                            .rvII2vi..         ...     ..:
        ..   .YZBBbv:.  .....  .iuPSv.  .....rIdgKjr:.  .       ..:......     ....:::ru21r:      .....:::..     .       ..7UZZPsi....     ...      ...
         .   :7XPPur:. ....... .iuS5r...:::::v5ZdS7i..      ..:rvu251jsYr:     ..:::ivSdXL:    ..irLJSKKIj7:..           .rIZQgKvrii::.. .         . .
          ..:ivLsL7i:.....:.....:LSUr...r7r:ivKdZIv:.       .:71dMBBQMgPUr.     ....:rIKSr.   .:7JqdQBBBQd5r:.          ..iuMQBb2vYv7::..             
          .i7jY7iii:.......... .:Y557:.i7vriiL5ZP57i..     .:rsPRBBBBBQgI7.      . ..iL5ui    :rjdgBBBBBQM5v:.            :sdBQdusYsvr:..      .      
          .7SKUr:.:.............iYqXJrirLv7ii7SPPu7:.       :rUEBBBBBBBgK7:.     ....i1KIr.   :rUEBBBQBBBRqvi.            .iXgRKJ7vvvri:.             
          :jdgUr................r1qbIY7vvLriivIPXur:..      .iYPMBBBBBQZ27:.   . ...:YXEXv.   .:7SgBQBQBBg2v:.             iuPP27rirrv7r..            
.         i2ggSi. .............:7uPPP2jLvri:i72KqULri:.     .:7uPZQRRZbIYi.       ..iYPbKL:    .i75PMMQgE5Jr:..          .:rU55vr:::r7J7i.            
         .i5Dg1i.  ....:.... ..:rY1XSIsvi:..:rYSqPI2svi:     ..irvYJLv7r:.         .ijXPIs:.    .:i77sLv7ri:..        .:i7L11J7r:...:v11r:.        . .
.     ...:72PKJ:. ....:::..   ..ii7vJL7i:.  .:7JXqbPPUvi.       ........          .:7UqXSJ7:.     . .......           .isSPX1ri..   :722si...       . 
     ..::r7ujJri.. ..::::..    .:::iiri:.    .:7Y1US52vr:.                     . .:L5DgMdPu7:.                       ..rJqK5vi..    .71Su7:..      ...
    ..:ivLJvri::... ..:::..   ......:::..   ..::iir7YLvri....                .:ir72PRQBBQDP1Lr:..                   ..:i7vs7r:... ..:71I5sr:.         
   ..:ivUKu7:..:..  .:::...........::::::..  ....::rv1uuv7rri:..         .:r7jUSKPPbPPPPSXUIU5U1vri::.         .:ir77777rrii::...::r7J1XS2vi.         
   .::rsPPIi.  .:.. .::::.::::::::i:iirrri:.....:.:rs2qKXISUUY7:.       .i1PRgMZZK2Lrii:iirv2PgMgqSJvi:.     .:rs2PPdq5Jvriiiiiiir7Y11ISPXui.         
   .:rv5KKYi.  .:....::iiiirr77vvLvLLYLjss7riiii::.:i7vssU2SSq2ULvrr777vLU5bPPSIJYri......:rv5qEPdbEPPIUJsvYYu1XXPKX2UYv777Ls1JusUIKS2JSbDX7.         
    :7US5Yr:. ..:::.:.::r7YYuuI2SSXSK5X5SUIjjYs7r:......:i7vjUXKEZMgQQQgZS17ririi:::::::::iirr777YUKgQBBBBBBBgEX2vri::ii7L2SPPEqPqEPPuJ2EgZs:         
    :vUXJ7:......::::::r7sj2155XXPKPqPKqXK5SI2usri.... ....ii77J1KPdPdPP2j7riiiiirirrrrrrrrrii:::irY2PEMRBRMPSY7i:...::7vU5bEDEEPbbPSUs5bMPj:.        
    :7I5Ji... ....::::irYJUUI2XSKXKKPXqXKSS2I2UJLri::.........::iirr7rriiirrrr7r7777v7v77rrrrii:i:::ir7LuuuL7::.. ..:r7sU2KKPqPPPKK5I12Sddqv:.
